server:
  port: 8000
#整合数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.71.100:3306/gulimall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
  #配置Nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-member
#整合mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml

