server:
  port: 10001
#整合数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.71.100:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
  #配置Nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-product
#整合mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: showStatus # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    com.atguigu.gulimall: debug
