server:
  port: 10002
#spring配置
spring:
  application:
    name: gulimall-product
  datasource:
    url: jdbc:mysql://192.168.71.100:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
#  cloud配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
# mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:/mapper/**/*.xml
#日志配置
logging:
  level:
    com.atguigu.gulimall: debug
